export const XuanceModule = {
    ACCOUNT: {
        LOGIN_SUCCESS: "ACCOUNT.LOGIN_SUCCESS",
        LOGIN_FAILED: "ACCOUNT.LOGIN_FAILED",
        INIT: "ACCOUNT.INIT",
        SCRIPT: {
            ADPOP: "ACCOUNT.SCRIPT.ADPOP",
            COOKIE_UPDATER: "ACCOUNT.SCRIPT.COOKIE_UPDATER",
            INIT_LOGIN_CHECKER: "ACCOUNT.SCRIPT.INIT_LOGIN_CHECKER",
            LOGIN_STATUS_FAIL_CHECKER: "ACCOUNT.SCRIPT.LOGIN_STATUS_FAIL_CHECKER",
            SLIDE_VERIFY_CHECKER: "ACCOUNT.SCRIPT.SLIDE_VERIFY_CHECKER"
        },
        IPC: {
            ON: {
                RENDERER_READY: "ACCOUNT.IPC.ON.RENDERER_READY",
                INIT_LOGIN_SUCCESS: "ACCOUNT.IPC.ON.INIT_LOGIN_SUCCESS",
                INIT_LOGIN_FAILED: "ACCOUNT.IPC.ON.INIT_LOGIN_FAILED",
                CLICK_ACCOUNT_ITEM: "ACCOUNT.IPC.ON.CLICK_ACCOUNT_ITEM",
                CLICK_ADD_ACCOUNT_BUTTON: "ACCOUNT.IPC.ON.CLICK_ADD_ACCOUNT_BUTTON",
                UPDATE_COOKIES: "ACCOUNT.IPC.ON.UPDATE_COOKIES",
                OPEN_DEBUG: "ACCOUNT.IPC.ON.OPEN_DEBUG",
                LOGIN_STATUS_CHANGE_TO_FAILED: "ACCOUNT.IPC.ON.LOGIN_STATUS_CHANGE_TO_FAILED",
                SLIDE_VERIFICATION_POPUP_DETECTED: "ACCOUNT.IPC.ON.SLIDE_VERIFICATION_POPUP_DETECTED",
                SLIDE_VERIFICATION_POPUP_HIDDEN: "ACCOUNT.IPC.ON.SLIDE_VERIFICATION_POPUP_HIDDEN",
                HIDE_ACCOUNT_VIEW: "ACCOUNT.IPC.ON.HIDE_ACCOUNT_VIEW",
                RENDERER_LOG: "ACCOUNT.IPC.ON.RENDERER_LOG"
            },
            SEND: "ACCOUNT.IPC.SEND"
        },
        STATE: {
            INIT: "ACCOUNT.STATE.INIT",
            DISPATCH: "ACCOUNT.STATE.DISPATCH",
            IDLE: "ACCOUNT.STATE.IDLE",
            WORKING: "ACCOUNT.STATE.WORKING",
            WORKING_EXCEPTION: "ACCOUNT.STATE.WORKING_EXCEPTION",
            IDLE_EXCEPTION: "ACCOUNT.STATE.IDLE_EXCEPTION",
            OFFLINE: "ACCOUNT.STATE.OFFLINE",
            NOT_LOGINED: "ACCOUNT.STATE.NOT_LOGINED"
        },
        VIEW: {
            CREATE_INVISIBLE_VIEW: "ACCOUNT.VIEW.CREATE_INVISIBLE_VIEW",
            INIT_ACCOUNT_PAGE: "ACCOUNT.VIEW.INIT_ACCOUNT_PAGE",
            SET_ACTIVE_VIEW: "ACCOUNT.VIEW.SET_ACTIVE_VIEW",
            REMOVE_VIEW: "ACCOUNT.VIEW.REMOVE_VIEW"
        },
        ENV: {
            INIT_STORE: "ACCOUNT.ENV.INIT_STORE",
            SAVE_COOKIES: "ACCOUNT.ENV.SAVE_COOKIES",
            SAVE_ACCOUNT: "ACCOUNT.ENV.SAVE_ACCOUNT",
            DELETE_ALL_ACCOUNT: "ACCOUNT.ENV.DELETE_ALL_ACCOUNT",
            LOAD_ACCOUNT_LIST: "ACCOUNT.ENV.LOAD_ACCOUNT_LIST",
            APPLY_COOKIE_TO_SESSION: "ACCOUNT.ENV.APPLY_COOKIE_TO_SESSION"
        }
    },
    PLUGIN: {
        HOOK: {
            SCRIPT: {
                COLLECT_ARTICLE: {
                    ONLY_KEY_WORD: "PLUGIN.HOOK.SCRIPT.COLLECT_ARTICLE.ONLY_KEY_WORD",
                    USER_AND_KEYWORD: "PLUGIN.HOOK.SCRIPT.COLLECT_ARTICLE.USER_AND_KEYWORD"
                }
            },
            IPC: {
                SEND_ARTICLE_DATA: "PLUGIN.HOOK.IPC.SEND_ARTICLE_DATA",
                SEND_COMMENT_DATA: "PLUGIN.HOOK.IPC.SEND_COMMENT_DATA",
                SEND_CAPTCHA: "PLUGIN.HOOK.IPC.SEND_CAPTCHA",
                SEND_ARTICLE_INTERACTION: "PLUGIN.HOOK.IPC.SEND_ARTICLE_INTERACTION"
            }
        }
    },
    HANDLER: {
        DISPATCH: {
            COLLECT_ARTICLE: "HANDLER.DISPATCH.COLLECT_ARTICLE",
            COLLECT_COMMENT: "HANDLER.DISPATCH.COLLECT_COMMENT",
            COMMON: "HANDLER.DISPATCH.COMMON"
        },
        RECEIVE_HANDLER: {
            COLLECT_ARTICLE: "HANDLER.RECEIVE_HANDLER.COLLECT_ARTICLE",
            COLLECT_COMMENT: "HANDLER.RECEIVE_HANDLER.COLLECT_COMMENT",
            COLLECT_ARTICLE_INTERACTION: "HANDLER.RECEIVE_HANDLER.COLLECT_ARTICLE_INTERACTION"
        },
        RECEIVE_PRE_HANDLER: {
            COLLECT_ARTICLE: "HANDLER.RECEIVE_PRE_HANDLER.COLLECT_ARTICLE"
        },
        SEND_PRE_HANDLER: {
            COLLECT_ARTICLE: "HANDLER.SEND_PRE_HANDLER.COLLECT_ARTICLE",
            CONNECT_ARTICLE_INTERACTION: "HANDLER.SEND_PRE_HANDLER.CONNECT_ARTICLE_INTERACTION"
        }
    },
    ROUTE: {
        RECEIVE: "ROUTE.RECEIVE",
        RECEIVE_PRE: "ROUTE.RECEIVE_PRE",
        SEND: "ROUTE.SEND",
        SEND_PRE: "ROUTE.SEND_PRE"
    },
    QUEUE: {
        RECEIVE: "QUEUE.RECEIVE",
        RECEIVE_DELAY: "QUEUE.RECEIVE_DELAY",
        SEND: "QUEUE.SEND",
        SEND_DELAY: "QUEUE.SEND_DELAY",
        SIMPLE: "QUEUE.SIMPLE"
    },
    WEBSOCKET: {
        TRY_FALLBACK_CONNECTION: "WEBSOCKET.TRY_FALLBACK_CONNECTION",
        UPDATE_HEARTBEAT: "WEBSOCKET.UPDATE_HEARTBEAT",
        HEARTBEAT_TIMEOUT: "WEBSOCKET.HEARTBEAT_TIMEOUT",
        RECONNECT: "WEBSOCKET.RECONNECT",
        SEND_PING: "WEBSOCKET.SEND_PING",
        CREATE_WS_CLIENT: "WEBSOCKET.CREATE_WS_CLIENT",
        REMOVE_CLIENT: "WEBSOCKET.REMOVE_CLIENT",
        SEND_MESSAGE: "WEBSOCKET.SEND_MESSAGE",
        ON_MESSAGE: "WEBSOCKET.ON_MESSAGE",
        ON_DISCONNECT: "WEBSOCKET.ON_DISCONNECT",
        ADD_CLIENT: "WEBSOCKET.ADD_CLIENT",
        ON_CLOSE: "WEBSOCKET.ON_CLOSE",
        ON_ERROR: "WEBSOCKET.ON_ERROR",
        HANDLE_MSG_ERROR: "WEBSOCKET.HANDLE_MSG_ERROR",
        SCHEDULE_RECONNECT: "WEBSOCKET.SCHEDULE_RECONNECT",
        STATE_CHANGE: 'WEBSOCKET.STATE_CHANGE',
        STATE_CHECK: 'WEBSOCKET.STATE_CHECK',
        RECEIVE_PING: 'WEBSOCKET.RECEIVE_PING',
        RECEIVE_PONG: 'WEBSOCKET.RECEIVE_PONG'
    },
    SYSTEM: {
        DIALOG: "SYSTEM.DIALOG",
        ERROR: "SYSTEM.ERROR",
        INFO: "SYSTEM.INFO",
        WARNING: "SYSTEM.WARNING",
        POWER: "SYSTEM.POWER",
        APP: {
            START: "SYSTEM.APP.START",
            EXIT: "SYSTEM.APP.EXIT",
            RELAUNCH: "SYSTEM.APP.RELAUNCH"
        },
        API: "SYSTEM.API"
    },
    TASK: {
        PERSISTENCE: "TASK.PERSISTENCE",
        RECOVERY: "TASK.RECOVERY",
        TIMEOUT: "TASK.TIMEOUT",
        ERROR: "TASK.ERROR"
    },
    COMMON: {
        NETWORK: "COMMON.NETWORK",
        LOGGER: "COMMON.LOGGER",
        UPLOAD_FILE: "COMMON.UPLOAD_FILE"
    }
};